/**
 * Generate an HTML screenshot of the iteration-5 test output.
 *
 * Run with:
 *   npx tsx scripts/generate-iteration5-test-output-screenshot.ts
 *
 * Produces:
 *   screenshots/iteration5-tests-output.html
 *   screenshots/iteration5-tests-output.png (via Playwright, optional)
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { execSync } from "node:child_process";

const root = path.resolve(__dirname, "..");
const screenshotsDir = path.join(root, "screenshots");
fs.mkdirSync(screenshotsDir, { recursive: true });

// Run the iteration-5 tests and capture the output.
console.log("Running iteration 5 tests...");
let output = "";
try {
  output = execSync("npx tsx tests/run-iteration5-tests.ts 2>&1", {
    cwd: root,
    encoding: "utf8",
    timeout: 180000,
    stdio: ["pipe", "pipe", "pipe"],
  });
} catch (err: any) {
  output = err.stdout ?? err.stderr ?? String(err);
}
console.log("Test output captured.");

// Strip the noisy log lines (info/debug) to keep the screenshot readable.
const cleanedLines = output
  .split("\n")
  .filter((line) => {
    // Keep test result lines and section headers.
    if (line.startsWith("──") || line.startsWith("  ✓") || line.startsWith("  ✗")) return true;
    if (line.startsWith("      →")) return true;
    if (line.startsWith("Iteration 5:")) return true;
    if (line.startsWith("Failures:")) return true;
    if (line.startsWith("  - ")) return true;
    if (line.trim() === "") return true;
    // Drop winston log lines.
    if (/\[(info|debug|warn|error)\]/.test(line)) return false;
    if (line.includes("migrations.") || line.includes("database.")) return false;
    if (line.includes("eventbus.")) return false;
    return false;
  })
  .join("\n");

const passed = (output.match(/✓/g) || []).length;
const failed = (output.match(/✗/g) || []).length;

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Iteration 5 — Test Output</title>
<style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',
                 'Helvetica Neue', Arial, sans-serif;
    background: #0d1117;
    color: #c9d1d9;
    margin: 0;
    padding: 32px;
    line-height: 1.5;
  }
  h1 {
    color: #58a6ff;
    border-bottom: 1px solid #21262d;
    padding-bottom: 12px;
    margin-top: 0;
  }
  .summary {
    display: inline-block;
    padding: 8px 16px;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 24px;
    background: ${failed === 0 ? "#1a7f37" : "#cf222e"};
    color: #fff;
  }
  pre {
    background: #161b22;
    border: 1px solid #21262d;
    border-radius: 6px;
    padding: 20px;
    font-family: 'SF Mono', Monaco, Menlo, Consolas, 'Courier New', monospace;
    font-size: 13px;
    line-height: 1.6;
    overflow-x: auto;
    color: #c9d1d9;
    white-space: pre-wrap;
    word-break: break-word;
  }
  .pass { color: #3fb950; }
  .fail { color: #f85149; }
  .info { color: #58a6ff; }
  .header { color: #d2a8ff; font-weight: bold; }
  .meta { color: #8b949e; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<h1>Iteration 5 — Test Output</h1>
<div class="summary">${passed} passed, ${failed} failed</div>
<pre>${cleanedLines
  .replace(/✓/g, '<span class="pass">✓</span>')
  .replace(/✗/g, '<span class="fail">✗</span>')
  .replace(/── ([^─]+) ──/g, '<span class="header">── $1 ──</span>')
  .replace(/Iteration 5: (\d+ passed, \d+ failed)/g, '<span class="info">Iteration 5: $1</span>')
}</pre>
<div class="meta">
  Generated by <code>scripts/generate-iteration5-test-output-screenshot.ts</code><br>
  Test file: <code>tests/run-iteration5-tests.ts</code> (67 tests)<br>
  Command: <code>npx tsx tests/run-iteration5-tests.ts</code>
</div>
</body>
</html>
`;

const htmlPath = path.join(screenshotsDir, "iteration5-tests-output.html");
fs.writeFileSync(htmlPath, html, "utf8");
console.log(`HTML screenshot written to: ${htmlPath}`);
