/**
 * Generate an HTML screenshot of the build verification output.
 *
 * Run with:
 *   npx tsx scripts/generate-iteration5-build-verification.ts
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { execSync } from "node:child_process";

const root = path.resolve(__dirname, "..");
const screenshotsDir = path.join(root, "screenshots");
fs.mkdirSync(screenshotsDir, { recursive: true });

console.log("Running npm run build...");
let buildOutput = "";
let buildOk = true;
try {
  buildOutput = execSync("npm run build 2>&1", {
    cwd: root,
    encoding: "utf8",
    timeout: 240000,
  });
} catch (err: any) {
  buildOk = false;
  buildOutput = err.stdout ?? err.stderr ?? String(err);
}
console.log("Build output captured.");

// Verify the dist/renderer/index.html exists.
const indexHtml = path.join(root, "dist", "renderer", "index.html");
const distExists = fs.existsSync(indexHtml);

// Run all iteration tests.
const testRuns: Array<{ name: string; output: string; passed: number; failed: number }> = [];
for (const t of [
  "run-all-tests",
  "run-iteration2-tests",
  "run-iteration3-tests",
  "run-iteration4-tests",
  "run-iteration5-tests",
]) {
  console.log(`Running ${t}...`);
  let out = "";
  try {
    out = execSync(`npx tsx tests/${t}.ts 2>&1`, {
      cwd: root,
      encoding: "utf8",
      timeout: 180000,
    });
  } catch (err: any) {
    out = err.stdout ?? err.stderr ?? String(err);
  }
  // Look for the summary line at the very end of each test runner.
  // Iteration 1 format: "  Total: 35  |  Passed: 35  |  Failed: 0"
  // Iteration N format: "  Iteration N: 35 passed, 0 failed"
  const totalMatch = out.match(/Total:\s*\d+\s*\|\s*Passed:\s*(\d+)\s*\|\s*Failed:\s*(\d+)/);
  const iterMatch  = out.match(/Iteration \d+:\s*(\d+)\s*passed,\s*(\d+)\s*failed/);
  const m = totalMatch ?? iterMatch;
  testRuns.push({
    name: t,
    output: out,
    passed: m ? parseInt(m[1], 10) : 0,
    failed: m ? parseInt(m[2], 10) : 0,
  });
}

const totalPassed = testRuns.reduce((s, r) => s + r.passed, 0);
const totalFailed = testRuns.reduce((s, r) => s + r.failed, 0);

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Iteration 5 — Build & Test Verification</title>
<style>
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto',
                 'Helvetica Neue', Arial, sans-serif;
    background: #0d1117;
    color: #c9d1d9;
    margin: 0;
    padding: 32px;
    line-height: 1.5;
  }
  h1 { color: #58a6ff; border-bottom: 1px solid #21262d; padding-bottom: 12px; margin-top: 0; }
  h2 { color: #d2a8ff; margin-top: 32px; }
  .summary {
    display: inline-block;
    padding: 8px 16px;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    margin-bottom: 24px;
    color: #fff;
  }
  .summary.ok  { background: #1a7f37; }
  .summary.bad { background: #cf222e; }
  pre {
    background: #161b22;
    border: 1px solid #21262d;
    border-radius: 6px;
    padding: 16px;
    font-family: 'SF Mono', Monaco, Menlo, Consolas, 'Courier New', monospace;
    font-size: 12px;
    line-height: 1.5;
    overflow-x: auto;
    color: #c9d1d9;
    white-space: pre-wrap;
    word-break: break-word;
    max-height: 400px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 24px;
  }
  th, td {
    text-align: left;
    padding: 8px 12px;
    border-bottom: 1px solid #21262d;
  }
  th { color: #58a6ff; font-weight: 600; }
  .pass { color: #3fb950; font-weight: 600; }
  .fail { color: #f85149; font-weight: 600; }
  .meta { color: #8b949e; font-size: 12px; margin-top: 24px; }
</style>
</head>
<body>
<h1>Iteration 5 — Build &amp; Test Verification</h1>

<div class="summary ${buildOk && distExists ? "ok" : "bad"}">
  ${buildOk && distExists ? "✓ BUILD PASSED" : "✗ BUILD FAILED"}
</div>
<div class="summary ${totalFailed === 0 ? "ok" : "bad"}">
  ${totalPassed} tests passed, ${totalFailed} failed
</div>

<h2>Build output</h2>
<pre>${buildOutput
  .replace(/</g, "&lt;")
  .replace(/>/g, "&gt;")}
</pre>

<h2>Test summary</h2>
<table>
  <thead>
    <tr><th>Test suite</th><th>Passed</th><th>Failed</th><th>Status</th></tr>
  </thead>
  <tbody>
    ${testRuns
      .map(
        (r) => `<tr>
      <td><code>${r.name}.ts</code></td>
      <td class="pass">${r.passed}</td>
      <td class="${r.failed > 0 ? "fail" : "pass"}">${r.failed}</td>
      <td>${r.failed === 0 ? "✓" : "✗"}</td>
    </tr>`,
      )
      .join("\n")}
    <tr style="font-weight: 600; background: #161b22;">
      <td>TOTAL</td>
      <td class="pass">${totalPassed}</td>
      <td class="${totalFailed > 0 ? "fail" : "pass"}">${totalFailed}</td>
      <td>${totalFailed === 0 ? "✓" : "✗"}</td>
    </tr>
  </tbody>
</table>

<h2>dist/renderer/index.html</h2>
<pre>${distExists ? "✓ File exists — Vite build completed successfully." : "✗ File missing — Vite build did not produce output."}</pre>

<div class="meta">
  Generated by <code>scripts/generate-iteration5-build-verification.ts</code><br>
  Date: ${new Date().toISOString()}<br>
  Repo: <code>github.com/Vtheonly/AgentGithubUplaod</code>
</div>
</body>
</html>
`;

const outPath = path.join(screenshotsDir, "iteration5-build-verification.html");
fs.writeFileSync(outPath, html, "utf8");
console.log(`HTML screenshot written to: ${outPath}`);
console.log(`Total: ${totalPassed} passed, ${totalFailed} failed`);
